.dockerignore
Dockerfile
README.md

Created the Dockerfile to deploy the module with docker and also updated the README to add information about the creation of the image.

Proper dockerfile with corresponding README update

---

src/components/PrescriptionMenu.tsx
src/pages/Call.tsx

fix of grids in private comments of the doctor

fix: :art: fix of grids in private comments of the doctor

---

src/pages/inperson/InPersonAppoinment.tsx
src/pages/inperson/SelectorSection.jsx

Leftover style boxes skipped, when height is less than 'md' it doesn't get 100% complete

refactor: section selector maintenance and refactor

---

src/pages/Settingsnew.tsx

fix: Writing error

---

src/components/LoadAppointments.tsx
src/pages/Home.tsx

feat: Selecting appointment types

---

src/components/LoadAppointments.tsx
src/pages/Home.tsx

Daily Appointment Screen Element Updates
The reopen button should not be displayed on canceled appointments Hide citation detail hypertext, temporarily Hide edit button in private appointments, for doctor's unavailable hours. Hide notification button, temporarily Update edit buttons on open appointments and update video call button on face-to-face appointments

refactor: Daily Appointment Screen Element Updates

---

src/components/LoadAppointments.tsx

Added locked appointment status in calendar

feat: Added locked appointment status in calendar

---

src/components/LoadAppointments.tsx

updated hours for some dating statuses

feat: updated hours for some dating statuses

---

.dockerignore
Dockerfile.dev
docker-compose-dev.yml

`docker compose -f docker-compose-dev.yml up --build` para levantar el contenedor
` docker-compose -f docker-compose-dev.yml down` para bajar

Se agregaron configuraciones para dockerizar en ambiente de desarrollo

---

src/components/StudiesMenuRemote.tsx

[Permitir al usuario filtrar sus estudios clínicos por categoría y fecha](https://www.figma.com/proto/s5QFKXhMS3Lcmpg5ZFb7Xo/Ecosistema-Boldo?node-id=7871:45259&starting-point-node-id=7798:43181)

724 agregar filtrado studies remote

---

src/components/LaboratoryMenu.tsx

Anexado link al prototipo del comportamiento esperado:
[]([https://www.figma.com/file/s5QFKXhMS3Lcmpg5ZFb7Xo/Ecosistema-Boldo?node-id=7871%3A45259](https://www.figma.com/file/s5QFKXhMS3Lcmpg5ZFb7Xo/Ecosistema-Boldo?node-id=7871:45259))

770 agregar filtrado studies inperson

---

src/components/LaboratoryMenu.tsx
src/components/StudiesMenuRemote.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=771

add button close modal

---

src/pages/Dashboard.tsx
src/pages/inperson/InPersonAppoinment.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=775

775 end appointment show inperson modify

---

src/components/StudiesMenuRemote.tsx

Quitar el scroll horizontal a los archivos adjuntos de los estudios:
https://www.figma.com/proto/s5QFKXhMS3Lcmpg5ZFb7Xo/Ecosistema-Boldo?node-id=7846%3A45403&starting-point-node-id=7798%3A43181

style:modify studies data style attached

---

src/components/StudiesMenuRemote.tsx

[ticket on the board](https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=781)

style: add studies load indicator in remote menu

---

src/pages/inperson/SelectorSection.jsx

fix: hover menu selection and fix up order

---

src/components/StudiesMenuRemote.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=788

feat: hide filtered data and ordering date

---

src/components/PrescriptionMenu.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=790

feat: in call appointment diagnosis auto saved

---

src/components/Layout.tsx
src/pages/Call.tsx
src/pages/Dashboard.tsx
src/pages/ValidatePatient.js
src/pages/inperson/PatientSection.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=963

963 fixings improvements

---

src/pages/inperson/MedicalRecordSection.jsx

Ticket relacionado: https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=1024

feat autofocus inperson soep

---

src/pages/Dashboard.tsx

reduce time intervals in schedule slots

---

package-lock.json
src/pages/Call.tsx
src/pages/inperson/MedicalRecordSection.jsx

update main reason focus

---

src/components/LaboratoryMenu.tsx
src/components/Layout.tsx
src/components/PrescriptionMenu.tsx
src/components/StudiesMenuRemote.tsx
src/pages/Call.tsx
src/pages/Dashboard.tsx
src/pages/Download.tsx
src/pages/ValidatePatient.js
src/pages/inperson/InPersonAppoinment.tsx
src/pages/inperson/MedicalRecordSection.jsx
src/pages/inperson/PatientSection.tsx
src/tailwind.css

Actualización de los cambios de dev en test
https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=1037

Update test from 1037-update-dev-into-test

---

src/pages/Call.tsx
src/pages/inperson/PatientSection.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=1056

hide first consultation and follow-up menu

---

src/components/LaboratoryMenu.tsx
src/components/StudiesMenuRemote.tsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=1098

1098 updated title and subtitle study order

---

src/pages/ValidatePatient.js

Reverts iHub-PTI/boldo-web#151

Revert "feat: The patient validation endpoints were updated"

---

package.json
src/pages/Settings.tsx

feat: optimize the profile photo uploaded by the doctor

---

package-lock.json
src/pages/inperson/InPersonAppoinment.tsx
src/pages/inperson/MedicalRecordSection.jsx

fix: does does not enable the button for ambulatory records

---

src/components/Stream.tsx

Reverts iHub-PTI/boldo-web#218

Revert "Setting environment variables for the iceServer"

---

src/components/MedicalHistory.tsx
src/components/MedicalHistoryCall.tsx
src/pages/Call.tsx
src/pages/inperson/MedicalRecordSection.jsx

https://dev.azure.com/programaboldo/DT.698%20-%20EBT/_boards/board/t/Frontend/Subactividad/?workitem=1527

1527 list of changes

---

src/components/upload-studies/OrderImported.tsx
src/components/upload-studies/StudyForm.tsx
src/pages/Settings.tsx

Reverts iHub-PTI/boldo-web#243

Revert "update presigned structure"
